### ISSUE TITLE
Prepare for BETA release

### ISSUE THREAD

**Issue by iamhyc** [iamhyc/mind-flash#1]
### History 特性
- [x] `historyWidget`重构，自定义绘制QListWidgetItem，更改vertical scrollbar stylesheet
- [x] `historyWidget`添加圆角，`historyItem`添加圆角和阴影（参数询问pro）
- [x] `history`条目可 双击 提取，并放在inputbox中

### Todo 特性
- [x] 默认展示一个`todo_list`，在`input`上方；显示historyWdiget时隐藏
- [x] 无内容时，只有一个“todo list”的灰色小标题 (transparent background)，有内容时（背景alpha=75%）
- [x] `Alt+Q`以添加新条目 (将inputbox的内容添加到todolist，不关闭窗体)，右键点击toggle item(切换strikeline style)
- [x] 当前条目全部完成后，自动加入`history`中并从`todo_list`移除，并关闭窗体

### InputBox 特性
- [x] inputbox 高度随文字内容自适应（换行后自动resize增加行高），但不超过给定值（4行）
- [x] 对于 `**bold_text**`，`*italic_text*`按照Markdown样式转换
- [x] 更改raw text中image label的显示~~转换为类HTML样式 `<img src="save_img_path" />`~~
- [x] 优化caret，~~在无输入时为保持显示而不是隐藏~~延长反应时间间隔为500ms
- [x] 尝试优化窗口失去焦点后，对内部快捷键记录的干扰（失去焦点后内部keyStroke记录清空）

**Comment by iamhyc** [comment]
* 默认展示一个`todo_list`，在输入框上方
* 无内容时，只有一个“todo list”的灰色小标题，点击以添加内容
* 有内容时，左键点击以添加新条目，右键点击以toggle完成条目
* 完成的条目在程序结束时，加入`history`中，并从`todo_list`移除

**Comment by iamhyc** [comment]
* `input`高度随文字内容自适应，不超过给定值（屏幕高度百分比）

**Comment by iamhyc** [comment]
### Miscs
- [ ] 将颜色和样式设置放在独立的配置文件中 (*.json)

**Comment by iamhyc** [comment]
The commit 52c5eb03592e3e7cc12a2773a2e47e613c97ea6d marks the major frameworks finished.
