### ISSUE TITLE
Prepare for v2.0

### ISSUE THREAD

**Issue by iamhyc** [iamhyc/mind-flash#10]
## Promotions for Version 2.0
Mind Flash定位**创造力工具**中的个人信息管理软件，快速捕捉你脑海中的每一个*不值一提* 的想法，整合碎片思维（mind-wandering），发掘属于你的Eureka Time。

**Phase I**

(v1.0.1, 98e32dd4631b903b3f9cd25f3eabfa5d2301302a)
- [x] `Ctrl+F`用于搜索，同时去掉case sensitive，优化toolbar切换逻辑
- [x] 修复每天第一条记录为非文字记录的保存错误
- [x] history widget打开时，回车键保存（并更新）但不退出
- [x] 增加application desktop file，可以通过快捷方式唤醒

(v1.0.5, b9240be38f41d9bad3079e448613feda464275a6)
- [x] topbar空白区域增加窗口拖动响应
- [x] dirty hack：如果按键为Enter/Return，则清空 key stroke 记录列表
- [x] 优化 `Ctrl+V` 响应：粘贴内容为 http(s)链接/image/file 时自动转换为Markdown格式，超链接渲染为<a> tag；`<-file:///->` tag deprecated（向上兼容）
- [x] 热更新支持：添加 `update icon` 和对应功能，每次开启超过5s，在hint bar处提示（包含版本号）
- [x] `颜色样式`，`按键绑定` 配置从 `config.json` 文件中导入为全局变量，按照widget分组存放在 `$HOME/.mf` 下；

**Phase II**

(v1.1.0)
- [ ] support pinned items: 单独存储，`Alt+Y`切换与普通pages的展示；不支持range切换
- [ ] history record添加themes聚类，文本第一行添加tag标签指定（无视大小写），无标签为`default/flush`；theme标签拟分为五个等级，leftmost到rightmost依次为：`eureka`, `idea`, `default/flush`, `note`, `material`；record上左右滑动可改变等级，颜色支持自定义；在 `~/.mf` 下存储现有的themes标签（及引用次数）
- [ ] topbar的filter icon支持按themes搜索
- [ ] 当设置有theme filter时，hint label追加显示theme，保存的text自动添加theme
- [ ] theme filter持久化，默认insert theme作为前缀（hint label默认追加显示default）

(v1.2.0)
- [ ] 重写 `mf_entity` 读取部分，并行化读取，并通过 回调函数/共享内存 实现异步有序渲染
- [ ] 右键操作放到右键菜单中实现，左键/双击操作也放到右键菜单中；topbar增加close icon
- [ ] 支持record 追加/修改 theme，通过右键菜单实现
- [ ] 右键菜单支持“引用”，“复制”，其中“复制”同现在的双击逻辑；
- [ ] “引用”参考论坛类实现，支持套娃引用，支持引用链接跳转（日期跳转+列表跳转）

**Phase III**

(v2.0.0)
- 切换到Qt5技术栈开发，调研下是否使用DTK样式
- 增加calendar日期跳转，支持多个日期段选择
- 限制`historyItem`高度，只加载和渲染 ListView 中固定数量的history，从而减少`historyWidget`内存占用
- 实现history preview widget，添加浮动的关闭按钮，同时支持右键菜单
- history widget展示时，record list即时渲染，并定位在最下方；减小record widget之间的间隔，最下方widget单独配置margins；
- 支持语音输入（显示为文件链接）/语音播放（显示为长条的voice message label）
- 支持内容分享（导出）到微信/QQ，通过第三方服务
- 增加周报/月报/年报功能
    - 字数/图片数/文件数 统计
    - 使用频率时段分布，使用强度（内容长度）时段统计
    - 词频分析（本地分割？）
