### ISSUE TITLE
Prepare for v1.0

### ISSUE THREAD

**Issue by iamhyc** [iamhyc/mind-flash#6]
### Notes for release v1.0.0
**Phase I** (v0.9.5): 0d7a7d89a2cbf53c022f3220c001511e2949cb90
- [x] Week Number后面加上是几月（上旬绿色调，中旬蓝色调，下旬红色调）
- [x] 优化History Hint颜色显示（用户名，@，日期），参考QQ
- [x] 保持焦点在inputbox
- [x] 优化keyFn封装
- [x] 优化render history时的reverse map record
- [x] ~~优化缩略图 焦点区域 选择~~ Display a floating preview widget
- [x] 支持双击提取条目支持移除（包括引用的图片）：第一次双击为提取，第二次双击为确认移除

**Phase II** (v0.9.6): 022fd204913f372d9a31f33e43dbea9fd882d348
- [x] 删除条目时，暂时不删除图片
- [x] 增加title bar widget切换：1) hint label; 2) tool bar; 3) input box.
        Switch Logic: default with `hint label`, **Hover Enter** to show `tool bar` (with left-aligned icon labels); **search icon** for `input box`.
- [x] 以 `export icon`为例实现功能，每个icon对应一个class做功能支持，将当前History List内容以Markdown格式导出到桌面（`$HOME/Desktop/`）

**Phase III** (v0.9.8): 4e7f83145a69ffe9514c96cdb5da7586daa2bb25
- [x] `Alt + V/H/J/K` 按键绑定放到全局；
- [x] Image Previewer增加滚轮调整大小，每次缩小50px，最小100px，最大3倍；
- [x] ~~Export path with dialog selection~~ （无法调用native样式，先不搞了）
- [x] 添加一个 日/周/月/年 的切换icon（tip是Alt+V）
- [x] When first use (home folder creation), show placeholder text: "**Try double click on me!**" or "**press ENTER to flush it!**"
- [x] 支持文本拖拽插入（HTML转换成plain text）
- [x] 在线URL拖拽保存为 \<a\> tag
- [x] 本地文件拖拽复制保存（保存在files文件夹下），history显示为file icon，tooltip显示文件名
- [x] file icon显示right-slided text，点击后以系统方式打开文件 [(reference)](https://doc.qt.io/qt-5/qdesktopservices.html#openUrl)
- [x] 列表按照pixel滚动：listView->setVerticalScrollMode(QAbstractItemView::ScrollPerPixel)
- [x] History List Widget增加滚轮事件，最上方时再向上滚动两次触发backward jump（并滚动到item[-1]），最下方时再向下滚动两次触发forward jump
- [x] 还有些bug：~~1) win平台删除item会闪退 2) Alt+V和history icon不同步 3) 某些情况KeysFn记录会出错，两个平台都有 4) savePixmap没有后缀~~

**Phase IV** (v1.0.0):
- [x] 添加一些tooltip
- [x] notify-send 内容改为显示在hint label上，延时不变
- [x] 分离history gui rendering logic，UI操作更跟手；现在瓶颈在I/O部分
- [x] updateHistory未完成时追加显示 "(loading...)"
- [x] search icon用filter icon替换，用regex实现，在render的时候过滤掉
- [x] Promotion
```
一个简单的个人信息管理工具，按照时间对 文字/截图/文件 内容展示。
温馨提示：将 .mf 文件夹加入您的云同步以获得跨平台体验，更好的组织您的工作内容。
```
```
新的GIF（显示click，显示key stroke）：
a) toggle 两次todo，然后删掉它；
b) 双击打开hisotry，里面有两条来自不同电脑的hello world记录；
c) 展示topbar并使用collapse，然后双击恢复；
d) 使用topbar切换一轮，向上滚动到比较长的一页，向下滚动回来
e) 拖拽一个pdf文件然后回车保存，重新打开history，然后结束
```

**Finished**:
- [x] 图片右键点击可复制，弹出toast提示/右键菜单复制
`notify-send -a "Mind-Flash" -i "$PWD/res/icons/pulse_heart.png" -t 1000 "Image Copied"`
- [x] [custom keybindings for gnome](https://unix.stackexchange.com/questions/323160/gnome3-adding-keyboard-custom-shortcuts-using-dconf-without-need-of-logging) and [custom keybindings for dde](https://bbs.deepin.org/archiver/?tid-148930.html)

**Comment by iamhyc** [comment]
### Highlight Functions （v2.0）
- 增加周报/月报/年报功能（统计内容暂定）
- 增加文件URI拖拽同步（request库判定文件内容/格式）

**Comment by iamhyc** [comment]
- [x] Fix Issue #3 
- [x] Fix Issue #8 
- [x] Fix Issue #9

**Comment by iamhyc** [comment]
投稿准备中，本次Mind Flash开发已完全结束，完结撒花~
下次重启预计在star数量超过25之时，まだ~
